// Sprite layer order (bottom to top)
export const LAYER_ORDER = ['shadow', 'backhair', 'bottom', 'top', 'head', 'hair', 'hat', 'weapon'] as const;
export type LayerKey = typeof LAYER_ORDER[number];

// Spritesheet layout: 1104×192 per layer, 4 rows × 23 cols, 48×48px per frame
// Rows: 0=South, 1=West, 2=East, 3=North
// Walk cols 0-2, Stand col 3, Attack cols 12-14
export const FRAME_W = 48;
export const FRAME_H = 48;
export const DIRECTIONS = { south: 0, west: 1, east: 2, north: 3 } as const;
export type Direction = keyof typeof DIRECTIONS;

export const ANIMATIONS = {
  idle:   { startCol: 3, frames: 1 },
  walk:   { startCol: 0, frames: 3 },
  attack: { startCol: 12, frames: 3 },
} as const;
export type AnimationKey = keyof typeof ANIMATIONS;

export type ChildPath = 'warrior' | 'rogue' | 'archer' | 'mage';

export const CLASS_DEFAULTS: Record<ChildPath, {
  label: string;
  emoji: string;
  color: string;
  description: string;
  head: string;
  hair: string;
  backhair: string;
  hat: string | null;
  top: string;
  bottom: string;
  weapon: string | null;
  shadow: string;
}> = {
  warrior: {
    label: 'Guerrier',      emoji: '⚔️',  color: '#EF5350',
    description: 'Fort et courageux. Taille-toi un chemin à travers les obstacles.',
    head: 'head1', hair: 'hair1', backhair: 'backhair1',
    hat: 'hat1', top: 'top1', bottom: 'bottom1', weapon: 'sword1', shadow: 'shadow',
  },
  rogue: {
    label: 'Voleur',        emoji: '🗡️',  color: '#7E57C2',
    description: 'Rapide et discret. Aucun défi ne lui résiste longtemps.',
    head: 'head2', hair: 'hair2', backhair: 'backhair1',
    hat: null, top: 'top3', bottom: 'bottom2', weapon: 'sword1_c2', shadow: 'shadow',
  },
  archer: {
    label: 'Archer',        emoji: '🏹',  color: '#66BB6A',
    description: 'Précis et patient. Vise juste à chaque fois.',
    head: 'head1', hair: 'hair3', backhair: 'backhair2',
    hat: 'hat3', top: 'top6', bottom: 'bottom3', weapon: 'bow1arrow1', shadow: 'shadow',
  },
  mage: {
    label: 'Mage',          emoji: '🧙',  color: '#42A5F5',
    description: 'Sage et curieux. La connaissance est son pouvoir.',
    head: 'head1', hair: 'hair4', backhair: 'backhair1',
    hat: 'hat5', top: 'top2', bottom: 'bottom1', weapon: 'spear1', shadow: 'shadow',
  },
};

export function getSpriteAsset(layer: LayerKey, key: string): number | undefined {
  return (SPRITE_ASSETS[layer] as Record<string, number>)[key];
}

export const SPRITE_ASSETS: Record<LayerKey, Record<string, number>> = {
  shadow: {
    shadow: require('@/assets/sprites/shadow/shadow.png'),
  },
  head: {
    head1: require('@/assets/sprites/head/head1.png'),
    head2: require('@/assets/sprites/head/head2.png'),
    head3: require('@/assets/sprites/head/head3.png'),
    head4: require('@/assets/sprites/head/head4.png'),
    head5: require('@/assets/sprites/head/head5.png'),
    head6: require('@/assets/sprites/head/head6.png'),
    head7: require('@/assets/sprites/head/head7.png'),
    head8: require('@/assets/sprites/head/head8.png'),
    head1_tone1: require('@/assets/sprites/head/head1_tone1.png'),
    head1_tone2: require('@/assets/sprites/head/head1_tone2.png'),
    head1_tone3: require('@/assets/sprites/head/head1_tone3.png'),
    head1_green: require('@/assets/sprites/head/head1_green.png'),
    head1_blue: require('@/assets/sprites/head/head1_blue.png'),
    head1_purple: require('@/assets/sprites/head/head1_purple.png'),
    head1_grey: require('@/assets/sprites/head/head1_grey.png'),
    head2_tone1: require('@/assets/sprites/head/head2_tone1.png'),
    head2_tone2: require('@/assets/sprites/head/head2_tone2.png'),
    head2_tone3: require('@/assets/sprites/head/head2_tone3.png'),
    head2_green: require('@/assets/sprites/head/head2_green.png'),
    head2_blue: require('@/assets/sprites/head/head2_blue.png'),
    head2_purple: require('@/assets/sprites/head/head2_purple.png'),
    head2_grey: require('@/assets/sprites/head/head2_grey.png'),
    head3_tone1: require('@/assets/sprites/head/head3_tone1.png'),
    head3_tone2: require('@/assets/sprites/head/head3_tone2.png'),
    head3_tone3: require('@/assets/sprites/head/head3_tone3.png'),
    head3_green: require('@/assets/sprites/head/head3_green.png'),
    head3_blue: require('@/assets/sprites/head/head3_blue.png'),
    head3_purple: require('@/assets/sprites/head/head3_purple.png'),
    head3_grey: require('@/assets/sprites/head/head3_grey.png'),
    head4_tone1: require('@/assets/sprites/head/head4_tone1.png'),
    head4_tone2: require('@/assets/sprites/head/head4_tone2.png'),
    head4_tone3: require('@/assets/sprites/head/head4_tone3.png'),
    head4_green: require('@/assets/sprites/head/head4_green.png'),
    head4_blue: require('@/assets/sprites/head/head4_blue.png'),
    head4_purple: require('@/assets/sprites/head/head4_purple.png'),
    head4_grey: require('@/assets/sprites/head/head4_grey.png'),
    head5_tone1: require('@/assets/sprites/head/head5_tone1.png'),
    head5_tone2: require('@/assets/sprites/head/head5_tone2.png'),
    head5_tone3: require('@/assets/sprites/head/head5_tone3.png'),
    head5_green: require('@/assets/sprites/head/head5_green.png'),
    head5_blue: require('@/assets/sprites/head/head5_blue.png'),
    head5_purple: require('@/assets/sprites/head/head5_purple.png'),
    head5_grey: require('@/assets/sprites/head/head5_grey.png'),
    head6_tone1: require('@/assets/sprites/head/head6_tone1.png'),
    head6_tone2: require('@/assets/sprites/head/head6_tone2.png'),
    head6_tone3: require('@/assets/sprites/head/head6_tone3.png'),
    head6_green: require('@/assets/sprites/head/head6_green.png'),
    head6_blue: require('@/assets/sprites/head/head6_blue.png'),
    head6_purple: require('@/assets/sprites/head/head6_purple.png'),
    head6_grey: require('@/assets/sprites/head/head6_grey.png'),
    head7_tone1: require('@/assets/sprites/head/head7_tone1.png'),
    head7_tone2: require('@/assets/sprites/head/head7_tone2.png'),
    head7_tone3: require('@/assets/sprites/head/head7_tone3.png'),
    head7_green: require('@/assets/sprites/head/head7_green.png'),
    head7_blue: require('@/assets/sprites/head/head7_blue.png'),
    head7_purple: require('@/assets/sprites/head/head7_purple.png'),
    head7_grey: require('@/assets/sprites/head/head7_grey.png'),
    head8_tone1: require('@/assets/sprites/head/head8_tone1.png'),
    head8_tone2: require('@/assets/sprites/head/head8_tone2.png'),
    head8_tone3: require('@/assets/sprites/head/head8_tone3.png'),
    head8_green: require('@/assets/sprites/head/head8_green.png'),
    head8_blue: require('@/assets/sprites/head/head8_blue.png'),
    head8_purple: require('@/assets/sprites/head/head8_purple.png'),
    head8_grey: require('@/assets/sprites/head/head8_grey.png'),
  },
  hair: {
    hair1:  require('@/assets/sprites/hair/hair1.png'),
    hair2:  require('@/assets/sprites/hair/hair2.png'),
    hair3:  require('@/assets/sprites/hair/hair3.png'),
    hair4:  require('@/assets/sprites/hair/hair4.png'),
    hair5:  require('@/assets/sprites/hair/hair5.png'),
    hair6:  require('@/assets/sprites/hair/hair6.png'),
    hair7:  require('@/assets/sprites/hair/hair7.png'),
    hair8:  require('@/assets/sprites/hair/hair8.png'),
    hair9:  require('@/assets/sprites/hair/hair9.png'),
    hair10: require('@/assets/sprites/hair/hair10.png'),
    hair11: require('@/assets/sprites/hair/hair11.png'),
    hair12: require('@/assets/sprites/hair/hair12.png'),
    hair1_tone1: require('@/assets/sprites/hair/hair1_tone1.png'),
    hair1_tone2: require('@/assets/sprites/hair/hair1_tone2.png'),
    hair1_tone3: require('@/assets/sprites/hair/hair1_tone3.png'),
    hair1_green: require('@/assets/sprites/hair/hair1_green.png'),
    hair1_blue: require('@/assets/sprites/hair/hair1_blue.png'),
    hair1_purple: require('@/assets/sprites/hair/hair1_purple.png'),
    hair1_grey: require('@/assets/sprites/hair/hair1_grey.png'),
    hair2_tone1: require('@/assets/sprites/hair/hair2_tone1.png'),
    hair2_tone2: require('@/assets/sprites/hair/hair2_tone2.png'),
    hair2_tone3: require('@/assets/sprites/hair/hair2_tone3.png'),
    hair2_green: require('@/assets/sprites/hair/hair2_green.png'),
    hair2_blue: require('@/assets/sprites/hair/hair2_blue.png'),
    hair2_purple: require('@/assets/sprites/hair/hair2_purple.png'),
    hair2_grey: require('@/assets/sprites/hair/hair2_grey.png'),
    hair3_tone1: require('@/assets/sprites/hair/hair3_tone1.png'),
    hair3_tone2: require('@/assets/sprites/hair/hair3_tone2.png'),
    hair3_tone3: require('@/assets/sprites/hair/hair3_tone3.png'),
    hair3_green: require('@/assets/sprites/hair/hair3_green.png'),
    hair3_blue: require('@/assets/sprites/hair/hair3_blue.png'),
    hair3_purple: require('@/assets/sprites/hair/hair3_purple.png'),
    hair3_grey: require('@/assets/sprites/hair/hair3_grey.png'),
    hair4_tone1: require('@/assets/sprites/hair/hair4_tone1.png'),
    hair4_tone2: require('@/assets/sprites/hair/hair4_tone2.png'),
    hair4_tone3: require('@/assets/sprites/hair/hair4_tone3.png'),
    hair4_green: require('@/assets/sprites/hair/hair4_green.png'),
    hair4_blue: require('@/assets/sprites/hair/hair4_blue.png'),
    hair4_purple: require('@/assets/sprites/hair/hair4_purple.png'),
    hair4_grey: require('@/assets/sprites/hair/hair4_grey.png'),
    hair5_tone1: require('@/assets/sprites/hair/hair5_tone1.png'),
    hair5_tone2: require('@/assets/sprites/hair/hair5_tone2.png'),
    hair5_tone3: require('@/assets/sprites/hair/hair5_tone3.png'),
    hair5_green: require('@/assets/sprites/hair/hair5_green.png'),
    hair5_blue: require('@/assets/sprites/hair/hair5_blue.png'),
    hair5_purple: require('@/assets/sprites/hair/hair5_purple.png'),
    hair5_grey: require('@/assets/sprites/hair/hair5_grey.png'),
    hair6_tone1: require('@/assets/sprites/hair/hair6_tone1.png'),
    hair6_tone2: require('@/assets/sprites/hair/hair6_tone2.png'),
    hair6_tone3: require('@/assets/sprites/hair/hair6_tone3.png'),
    hair6_green: require('@/assets/sprites/hair/hair6_green.png'),
    hair6_blue: require('@/assets/sprites/hair/hair6_blue.png'),
    hair6_purple: require('@/assets/sprites/hair/hair6_purple.png'),
    hair6_grey: require('@/assets/sprites/hair/hair6_grey.png'),
    hair7_tone1: require('@/assets/sprites/hair/hair7_tone1.png'),
    hair7_tone2: require('@/assets/sprites/hair/hair7_tone2.png'),
    hair7_tone3: require('@/assets/sprites/hair/hair7_tone3.png'),
    hair7_green: require('@/assets/sprites/hair/hair7_green.png'),
    hair7_blue: require('@/assets/sprites/hair/hair7_blue.png'),
    hair7_purple: require('@/assets/sprites/hair/hair7_purple.png'),
    hair7_grey: require('@/assets/sprites/hair/hair7_grey.png'),
    hair8_tone1: require('@/assets/sprites/hair/hair8_tone1.png'),
    hair8_tone2: require('@/assets/sprites/hair/hair8_tone2.png'),
    hair8_tone3: require('@/assets/sprites/hair/hair8_tone3.png'),
    hair8_green: require('@/assets/sprites/hair/hair8_green.png'),
    hair8_blue: require('@/assets/sprites/hair/hair8_blue.png'),
    hair8_purple: require('@/assets/sprites/hair/hair8_purple.png'),
    hair8_grey: require('@/assets/sprites/hair/hair8_grey.png'),
    hair9_tone1: require('@/assets/sprites/hair/hair9_tone1.png'),
    hair9_tone2: require('@/assets/sprites/hair/hair9_tone2.png'),
    hair9_tone3: require('@/assets/sprites/hair/hair9_tone3.png'),
    hair9_green: require('@/assets/sprites/hair/hair9_green.png'),
    hair9_blue: require('@/assets/sprites/hair/hair9_blue.png'),
    hair9_purple: require('@/assets/sprites/hair/hair9_purple.png'),
    hair9_grey: require('@/assets/sprites/hair/hair9_grey.png'),
    hair10_tone1: require('@/assets/sprites/hair/hair10_tone1.png'),
    hair10_tone2: require('@/assets/sprites/hair/hair10_tone2.png'),
    hair10_tone3: require('@/assets/sprites/hair/hair10_tone3.png'),
    hair10_green: require('@/assets/sprites/hair/hair10_green.png'),
    hair10_blue: require('@/assets/sprites/hair/hair10_blue.png'),
    hair10_purple: require('@/assets/sprites/hair/hair10_purple.png'),
    hair10_grey: require('@/assets/sprites/hair/hair10_grey.png'),
    hair11_tone1: require('@/assets/sprites/hair/hair11_tone1.png'),
    hair11_tone2: require('@/assets/sprites/hair/hair11_tone2.png'),
    hair11_tone3: require('@/assets/sprites/hair/hair11_tone3.png'),
    hair11_green: require('@/assets/sprites/hair/hair11_green.png'),
    hair11_blue: require('@/assets/sprites/hair/hair11_blue.png'),
    hair11_purple: require('@/assets/sprites/hair/hair11_purple.png'),
    hair11_grey: require('@/assets/sprites/hair/hair11_grey.png'),
    hair12_tone1: require('@/assets/sprites/hair/hair12_tone1.png'),
    hair12_tone2: require('@/assets/sprites/hair/hair12_tone2.png'),
    hair12_tone3: require('@/assets/sprites/hair/hair12_tone3.png'),
    hair12_green: require('@/assets/sprites/hair/hair12_green.png'),
    hair12_blue: require('@/assets/sprites/hair/hair12_blue.png'),
    hair12_purple: require('@/assets/sprites/hair/hair12_purple.png'),
    hair12_grey: require('@/assets/sprites/hair/hair12_grey.png'),
  },
  backhair: {
    backhair1: require('@/assets/sprites/backhair/backhair1.png'),
    backhair2: require('@/assets/sprites/backhair/backhair2.png'),
    backhair3: require('@/assets/sprites/backhair/backhair3.png'),
    backhair4: require('@/assets/sprites/backhair/backhair4.png'),
    backhair5: require('@/assets/sprites/backhair/backhair5.png'),
    backhair1_tone1: require('@/assets/sprites/backhair/backhair1_tone1.png'),
    backhair1_tone2: require('@/assets/sprites/backhair/backhair1_tone2.png'),
    backhair1_tone3: require('@/assets/sprites/backhair/backhair1_tone3.png'),
    backhair1_green: require('@/assets/sprites/backhair/backhair1_green.png'),
    backhair1_blue: require('@/assets/sprites/backhair/backhair1_blue.png'),
    backhair1_purple: require('@/assets/sprites/backhair/backhair1_purple.png'),
    backhair1_grey: require('@/assets/sprites/backhair/backhair1_grey.png'),
    backhair2_tone1: require('@/assets/sprites/backhair/backhair2_tone1.png'),
    backhair2_tone2: require('@/assets/sprites/backhair/backhair2_tone2.png'),
    backhair2_tone3: require('@/assets/sprites/backhair/backhair2_tone3.png'),
    backhair2_green: require('@/assets/sprites/backhair/backhair2_green.png'),
    backhair2_blue: require('@/assets/sprites/backhair/backhair2_blue.png'),
    backhair2_purple: require('@/assets/sprites/backhair/backhair2_purple.png'),
    backhair2_grey: require('@/assets/sprites/backhair/backhair2_grey.png'),
    backhair3_tone1: require('@/assets/sprites/backhair/backhair3_tone1.png'),
    backhair3_tone2: require('@/assets/sprites/backhair/backhair3_tone2.png'),
    backhair3_tone3: require('@/assets/sprites/backhair/backhair3_tone3.png'),
    backhair3_green: require('@/assets/sprites/backhair/backhair3_green.png'),
    backhair3_blue: require('@/assets/sprites/backhair/backhair3_blue.png'),
    backhair3_purple: require('@/assets/sprites/backhair/backhair3_purple.png'),
    backhair3_grey: require('@/assets/sprites/backhair/backhair3_grey.png'),
    backhair4_tone1: require('@/assets/sprites/backhair/backhair4_tone1.png'),
    backhair4_tone2: require('@/assets/sprites/backhair/backhair4_tone2.png'),
    backhair4_tone3: require('@/assets/sprites/backhair/backhair4_tone3.png'),
    backhair4_green: require('@/assets/sprites/backhair/backhair4_green.png'),
    backhair4_blue: require('@/assets/sprites/backhair/backhair4_blue.png'),
    backhair4_purple: require('@/assets/sprites/backhair/backhair4_purple.png'),
    backhair4_grey: require('@/assets/sprites/backhair/backhair4_grey.png'),
    backhair5_tone1: require('@/assets/sprites/backhair/backhair5_tone1.png'),
    backhair5_tone2: require('@/assets/sprites/backhair/backhair5_tone2.png'),
    backhair5_tone3: require('@/assets/sprites/backhair/backhair5_tone3.png'),
    backhair5_green: require('@/assets/sprites/backhair/backhair5_green.png'),
    backhair5_blue: require('@/assets/sprites/backhair/backhair5_blue.png'),
    backhair5_purple: require('@/assets/sprites/backhair/backhair5_purple.png'),
    backhair5_grey: require('@/assets/sprites/backhair/backhair5_grey.png'),
  },
  hat: {
    hat1:    require('@/assets/sprites/hat/hat1.png'),
    hat1_c1: require('@/assets/sprites/hat/hat1_c1.png'),
    hat1_c2: require('@/assets/sprites/hat/hat1_c2.png'),
    hat1_c3: require('@/assets/sprites/hat/hat1_c3.png'),
    hat2:    require('@/assets/sprites/hat/hat2.png'),
    hat2_c1: require('@/assets/sprites/hat/hat2_c1.png'),
    hat3:    require('@/assets/sprites/hat/hat3.png'),
    hat3_c1: require('@/assets/sprites/hat/hat3_c1.png'),
    hat4:    require('@/assets/sprites/hat/hat4.png'),
    hat5:    require('@/assets/sprites/hat/hat5.png'),
    hat5_c1: require('@/assets/sprites/hat/hat5_c1.png'),
    hat5_c2: require('@/assets/sprites/hat/hat5_c2.png'),
    hat6:    require('@/assets/sprites/hat/hat6.png'),
    hat6_c1: require('@/assets/sprites/hat/hat6_c1.png'),
  },
  top: {
    top0:  require('@/assets/sprites/top/top0.png'),
    top1:  require('@/assets/sprites/top/top1.png'),
    top2:  require('@/assets/sprites/top/top2.png'),
    top3:  require('@/assets/sprites/top/top3.png'),
    top4:  require('@/assets/sprites/top/top4.png'),
    top5:  require('@/assets/sprites/top/top5.png'),
    top6:  require('@/assets/sprites/top/top6.png'),
    top7:  require('@/assets/sprites/top/top7.png'),
    top8:  require('@/assets/sprites/top/top8.png'),
    top9:  require('@/assets/sprites/top/top9.png'),
    top10: require('@/assets/sprites/top/top10.png'),
    top11: require('@/assets/sprites/top/top11.png'),
    top12: require('@/assets/sprites/top/top12.png'),
    top0_tone1: require('@/assets/sprites/top/top0_tone1.png'),
    top0_tone2: require('@/assets/sprites/top/top0_tone2.png'),
    top0_tone3: require('@/assets/sprites/top/top0_tone3.png'),
    top0_green: require('@/assets/sprites/top/top0_green.png'),
    top0_blue: require('@/assets/sprites/top/top0_blue.png'),
    top0_purple: require('@/assets/sprites/top/top0_purple.png'),
    top0_grey: require('@/assets/sprites/top/top0_grey.png'),
    top1_tone1: require('@/assets/sprites/top/top1_tone1.png'),
    top1_tone2: require('@/assets/sprites/top/top1_tone2.png'),
    top1_tone3: require('@/assets/sprites/top/top1_tone3.png'),
    top1_green: require('@/assets/sprites/top/top1_green.png'),
    top1_blue: require('@/assets/sprites/top/top1_blue.png'),
    top1_purple: require('@/assets/sprites/top/top1_purple.png'),
    top1_grey: require('@/assets/sprites/top/top1_grey.png'),
    top2_tone1: require('@/assets/sprites/top/top2_tone1.png'),
    top2_tone2: require('@/assets/sprites/top/top2_tone2.png'),
    top2_tone3: require('@/assets/sprites/top/top2_tone3.png'),
    top2_green: require('@/assets/sprites/top/top2_green.png'),
    top2_blue: require('@/assets/sprites/top/top2_blue.png'),
    top2_purple: require('@/assets/sprites/top/top2_purple.png'),
    top2_grey: require('@/assets/sprites/top/top2_grey.png'),
    top3_tone1: require('@/assets/sprites/top/top3_tone1.png'),
    top3_tone2: require('@/assets/sprites/top/top3_tone2.png'),
    top3_tone3: require('@/assets/sprites/top/top3_tone3.png'),
    top3_green: require('@/assets/sprites/top/top3_green.png'),
    top3_blue: require('@/assets/sprites/top/top3_blue.png'),
    top3_purple: require('@/assets/sprites/top/top3_purple.png'),
    top3_grey: require('@/assets/sprites/top/top3_grey.png'),
    top4_tone1: require('@/assets/sprites/top/top4_tone1.png'),
    top4_tone2: require('@/assets/sprites/top/top4_tone2.png'),
    top4_tone3: require('@/assets/sprites/top/top4_tone3.png'),
    top4_green: require('@/assets/sprites/top/top4_green.png'),
    top4_blue: require('@/assets/sprites/top/top4_blue.png'),
    top4_purple: require('@/assets/sprites/top/top4_purple.png'),
    top4_grey: require('@/assets/sprites/top/top4_grey.png'),
    top5_tone1: require('@/assets/sprites/top/top5_tone1.png'),
    top5_tone2: require('@/assets/sprites/top/top5_tone2.png'),
    top5_tone3: require('@/assets/sprites/top/top5_tone3.png'),
    top5_green: require('@/assets/sprites/top/top5_green.png'),
    top5_blue: require('@/assets/sprites/top/top5_blue.png'),
    top5_purple: require('@/assets/sprites/top/top5_purple.png'),
    top5_grey: require('@/assets/sprites/top/top5_grey.png'),
    top6_tone1: require('@/assets/sprites/top/top6_tone1.png'),
    top6_tone2: require('@/assets/sprites/top/top6_tone2.png'),
    top6_tone3: require('@/assets/sprites/top/top6_tone3.png'),
    top6_green: require('@/assets/sprites/top/top6_green.png'),
    top6_blue: require('@/assets/sprites/top/top6_blue.png'),
    top6_purple: require('@/assets/sprites/top/top6_purple.png'),
    top6_grey: require('@/assets/sprites/top/top6_grey.png'),
    top7_tone1: require('@/assets/sprites/top/top7_tone1.png'),
    top7_tone2: require('@/assets/sprites/top/top7_tone2.png'),
    top7_tone3: require('@/assets/sprites/top/top7_tone3.png'),
    top7_green: require('@/assets/sprites/top/top7_green.png'),
    top7_blue: require('@/assets/sprites/top/top7_blue.png'),
    top7_purple: require('@/assets/sprites/top/top7_purple.png'),
    top7_grey: require('@/assets/sprites/top/top7_grey.png'),
    top8_tone1: require('@/assets/sprites/top/top8_tone1.png'),
    top8_tone2: require('@/assets/sprites/top/top8_tone2.png'),
    top8_tone3: require('@/assets/sprites/top/top8_tone3.png'),
    top8_green: require('@/assets/sprites/top/top8_green.png'),
    top8_blue: require('@/assets/sprites/top/top8_blue.png'),
    top8_purple: require('@/assets/sprites/top/top8_purple.png'),
    top8_grey: require('@/assets/sprites/top/top8_grey.png'),
    top9_tone1: require('@/assets/sprites/top/top9_tone1.png'),
    top9_tone2: require('@/assets/sprites/top/top9_tone2.png'),
    top9_tone3: require('@/assets/sprites/top/top9_tone3.png'),
    top9_green: require('@/assets/sprites/top/top9_green.png'),
    top9_blue: require('@/assets/sprites/top/top9_blue.png'),
    top9_purple: require('@/assets/sprites/top/top9_purple.png'),
    top9_grey: require('@/assets/sprites/top/top9_grey.png'),
    top10_tone1: require('@/assets/sprites/top/top10_tone1.png'),
    top10_tone2: require('@/assets/sprites/top/top10_tone2.png'),
    top10_tone3: require('@/assets/sprites/top/top10_tone3.png'),
    top10_green: require('@/assets/sprites/top/top10_green.png'),
    top10_blue: require('@/assets/sprites/top/top10_blue.png'),
    top10_purple: require('@/assets/sprites/top/top10_purple.png'),
    top10_grey: require('@/assets/sprites/top/top10_grey.png'),
    top11_tone1: require('@/assets/sprites/top/top11_tone1.png'),
    top11_tone2: require('@/assets/sprites/top/top11_tone2.png'),
    top11_tone3: require('@/assets/sprites/top/top11_tone3.png'),
    top11_green: require('@/assets/sprites/top/top11_green.png'),
    top11_blue: require('@/assets/sprites/top/top11_blue.png'),
    top11_purple: require('@/assets/sprites/top/top11_purple.png'),
    top11_grey: require('@/assets/sprites/top/top11_grey.png'),
    top12_tone1: require('@/assets/sprites/top/top12_tone1.png'),
    top12_tone2: require('@/assets/sprites/top/top12_tone2.png'),
    top12_tone3: require('@/assets/sprites/top/top12_tone3.png'),
    top12_green: require('@/assets/sprites/top/top12_green.png'),
    top12_blue: require('@/assets/sprites/top/top12_blue.png'),
    top12_purple: require('@/assets/sprites/top/top12_purple.png'),
    top12_grey: require('@/assets/sprites/top/top12_grey.png'),
  },
  bottom: {
    bottom0: require('@/assets/sprites/bottom/bottom0.png'),
    bottom1: require('@/assets/sprites/bottom/bottom1.png'),
    bottom2: require('@/assets/sprites/bottom/bottom2.png'),
    bottom3: require('@/assets/sprites/bottom/bottom3.png'),
    bottom4: require('@/assets/sprites/bottom/bottom4.png'),
    bottom5: require('@/assets/sprites/bottom/bottom5.png'),
    bottom6: require('@/assets/sprites/bottom/bottom6.png'),
    bottom7: require('@/assets/sprites/bottom/bottom7.png'),
    bottom8: require('@/assets/sprites/bottom/bottom8.png'),
    bottom0_tone1: require('@/assets/sprites/bottom/bottom0_tone1.png'),
    bottom0_tone2: require('@/assets/sprites/bottom/bottom0_tone2.png'),
    bottom0_tone3: require('@/assets/sprites/bottom/bottom0_tone3.png'),
    bottom0_green: require('@/assets/sprites/bottom/bottom0_green.png'),
    bottom0_blue: require('@/assets/sprites/bottom/bottom0_blue.png'),
    bottom0_purple: require('@/assets/sprites/bottom/bottom0_purple.png'),
    bottom0_grey: require('@/assets/sprites/bottom/bottom0_grey.png'),
    bottom1_tone1: require('@/assets/sprites/bottom/bottom1_tone1.png'),
    bottom1_tone2: require('@/assets/sprites/bottom/bottom1_tone2.png'),
    bottom1_tone3: require('@/assets/sprites/bottom/bottom1_tone3.png'),
    bottom1_green: require('@/assets/sprites/bottom/bottom1_green.png'),
    bottom1_blue: require('@/assets/sprites/bottom/bottom1_blue.png'),
    bottom1_purple: require('@/assets/sprites/bottom/bottom1_purple.png'),
    bottom1_grey: require('@/assets/sprites/bottom/bottom1_grey.png'),
    bottom2_tone1: require('@/assets/sprites/bottom/bottom2_tone1.png'),
    bottom2_tone2: require('@/assets/sprites/bottom/bottom2_tone2.png'),
    bottom2_tone3: require('@/assets/sprites/bottom/bottom2_tone3.png'),
    bottom2_green: require('@/assets/sprites/bottom/bottom2_green.png'),
    bottom2_blue: require('@/assets/sprites/bottom/bottom2_blue.png'),
    bottom2_purple: require('@/assets/sprites/bottom/bottom2_purple.png'),
    bottom2_grey: require('@/assets/sprites/bottom/bottom2_grey.png'),
    bottom3_tone1: require('@/assets/sprites/bottom/bottom3_tone1.png'),
    bottom3_tone2: require('@/assets/sprites/bottom/bottom3_tone2.png'),
    bottom3_tone3: require('@/assets/sprites/bottom/bottom3_tone3.png'),
    bottom3_green: require('@/assets/sprites/bottom/bottom3_green.png'),
    bottom3_blue: require('@/assets/sprites/bottom/bottom3_blue.png'),
    bottom3_purple: require('@/assets/sprites/bottom/bottom3_purple.png'),
    bottom3_grey: require('@/assets/sprites/bottom/bottom3_grey.png'),
    bottom4_tone1: require('@/assets/sprites/bottom/bottom4_tone1.png'),
    bottom4_tone2: require('@/assets/sprites/bottom/bottom4_tone2.png'),
    bottom4_tone3: require('@/assets/sprites/bottom/bottom4_tone3.png'),
    bottom4_green: require('@/assets/sprites/bottom/bottom4_green.png'),
    bottom4_blue: require('@/assets/sprites/bottom/bottom4_blue.png'),
    bottom4_purple: require('@/assets/sprites/bottom/bottom4_purple.png'),
    bottom4_grey: require('@/assets/sprites/bottom/bottom4_grey.png'),
    bottom5_tone1: require('@/assets/sprites/bottom/bottom5_tone1.png'),
    bottom5_tone2: require('@/assets/sprites/bottom/bottom5_tone2.png'),
    bottom5_tone3: require('@/assets/sprites/bottom/bottom5_tone3.png'),
    bottom5_green: require('@/assets/sprites/bottom/bottom5_green.png'),
    bottom5_blue: require('@/assets/sprites/bottom/bottom5_blue.png'),
    bottom5_purple: require('@/assets/sprites/bottom/bottom5_purple.png'),
    bottom5_grey: require('@/assets/sprites/bottom/bottom5_grey.png'),
    bottom6_tone1: require('@/assets/sprites/bottom/bottom6_tone1.png'),
    bottom6_tone2: require('@/assets/sprites/bottom/bottom6_tone2.png'),
    bottom6_tone3: require('@/assets/sprites/bottom/bottom6_tone3.png'),
    bottom6_green: require('@/assets/sprites/bottom/bottom6_green.png'),
    bottom6_blue: require('@/assets/sprites/bottom/bottom6_blue.png'),
    bottom6_purple: require('@/assets/sprites/bottom/bottom6_purple.png'),
    bottom6_grey: require('@/assets/sprites/bottom/bottom6_grey.png'),
    bottom7_tone1: require('@/assets/sprites/bottom/bottom7_tone1.png'),
    bottom7_tone2: require('@/assets/sprites/bottom/bottom7_tone2.png'),
    bottom7_tone3: require('@/assets/sprites/bottom/bottom7_tone3.png'),
    bottom7_green: require('@/assets/sprites/bottom/bottom7_green.png'),
    bottom7_blue: require('@/assets/sprites/bottom/bottom7_blue.png'),
    bottom7_purple: require('@/assets/sprites/bottom/bottom7_purple.png'),
    bottom7_grey: require('@/assets/sprites/bottom/bottom7_grey.png'),
    bottom8_tone1: require('@/assets/sprites/bottom/bottom8_tone1.png'),
    bottom8_tone2: require('@/assets/sprites/bottom/bottom8_tone2.png'),
    bottom8_tone3: require('@/assets/sprites/bottom/bottom8_tone3.png'),
    bottom8_green: require('@/assets/sprites/bottom/bottom8_green.png'),
    bottom8_blue: require('@/assets/sprites/bottom/bottom8_blue.png'),
    bottom8_purple: require('@/assets/sprites/bottom/bottom8_purple.png'),
    bottom8_grey: require('@/assets/sprites/bottom/bottom8_grey.png'),
  },
  weapon: {
    sword1:     require('@/assets/sprites/weapon/sword1.png'),
    sword1_c2:  require('@/assets/sprites/weapon/sword1_c2.png'),
    sword1_c3:  require('@/assets/sprites/weapon/sword1_c3.png'),
    bow1:       require('@/assets/sprites/weapon/bow1.png'),
    bow1arrow1: require('@/assets/sprites/weapon/bow1arrow1.png'),
    spear1:     require('@/assets/sprites/weapon/spear1.png'),
    spear1_c2:  require('@/assets/sprites/weapon/spear1_c2.png'),
    pickaxe1:   require('@/assets/sprites/weapon/pickaxe1.png'),
    shield1L:   require('@/assets/sprites/weapon/shield1L.png'),
    shield1R:   require('@/assets/sprites/weapon/shield1R.png'),
  },
};
